//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automated_Attendance_System.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BSS_STUDENT_VW
    {
        public int STUDENT_HEADER_ID { get; set; }
        public string STUDENT_ID { get; set; }
        public string STUDENT_NAME { get; set; }
        public string NICK_NAME { get; set; }
        public string PRESENT_ADDRESS { get; set; }
        public string PRES_THANA { get; set; }
        public string PRES_POST_CODE { get; set; }
        public string PRES_CITY { get; set; }
        public string PRES_DIVISION { get; set; }
        public string PRES_COUNTRY { get; set; }
        public string PERM_ADDRESS { get; set; }
        public string PERM_THANA { get; set; }
        public string PERM_POST_CODE { get; set; }
        public string PERM_CITY { get; set; }
        public string PERM_DIVISION { get; set; }
        public string PERM_COUNTRY { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string BIRTH_CITY { get; set; }
        public string BIRTH_COUNTRY { get; set; }
        public string PLACE_OF_BIRTH { get; set; }
        public Nullable<System.DateTime> ADMISSION_DATE { get; set; }
        public Nullable<int> ADMISSION_SESSION_ID { get; set; }
        public string ADMISSION_SESSION { get; set; }
        public Nullable<int> ADMISSION_CLASS_ID { get; set; }
        public string ADMISSION_CLASS { get; set; }
        public Nullable<int> ADMISSION_SECTION_ID { get; set; }
        public string ADMISSION_SECTION { get; set; }
        public Nullable<int> ADMISSION_SHIFT { get; set; }
        public string Expr1 { get; set; }
        public Nullable<int> SESSION_ID { get; set; }
        public string SESSION_NAME { get; set; }
        public Nullable<int> CLASS_ID { get; set; }
        public string CLASS_NAME { get; set; }
        public Nullable<int> SECTION_ID { get; set; }
        public string SECTION_NAME { get; set; }
        public Nullable<int> SHIFT { get; set; }
        public string CURRENT_SHIFT { get; set; }
        public Nullable<int> CAMPUS_ID { get; set; }
        public string CAMPUS { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public string GENDER { get; set; }
        public string RELIGION_ID { get; set; }
        public string RELIGION { get; set; }
        public string RES_PHONE { get; set; }
        public string MOBILE { get; set; }
        public string EMAIL { get; set; }
        public string BLOOD_GROUP { get; set; }
        public string NATIONALITY_ID { get; set; }
        public string NATIONALITY { get; set; }
        public string BIRTH_CERTIFICATE_NO { get; set; }
        public string PASSPORT_NO { get; set; }
        public string MEDICAL_HISTORY { get; set; }
        public string EMERGENCY_MEDICAL_ACTION { get; set; }
        public string FATHERS_NAME { get; set; }
        public string FATHER_EDUCATION { get; set; }
        public string FATHER_EDUCATION_DETAILS { get; set; }
        public string FATHER_OCCUPATION { get; set; }
        public string FATHER_OCCUPATION_DETAILS { get; set; }
        public string FATHER_OFFICE_ADDRESS { get; set; }
        public string FATHER_OFFICE_PHONE { get; set; }
        public string FATHER_MOBILE { get; set; }
        public string FATHER_NATIONAL_ID { get; set; }
        public string FATHER_PASSPORT_NO { get; set; }
        public string MOTHERS_NAME { get; set; }
        public string MOTHER_EDUCATION { get; set; }
        public string MOTHER_EDUCATION_DETAILS { get; set; }
        public string MOTHER_OCCUPATION { get; set; }
        public string MOTHER_OCCUPATION_DETAILS { get; set; }
        public string MOTHER_OFFICE_ADDRESS { get; set; }
        public string MOTHER_OFFICE_PHONE { get; set; }
        public string MOTHER_MOBILE { get; set; }
        public string MOTHER_NATIONAL_ID { get; set; }
        public string MOHER_PASSPORT_NO { get; set; }
        public string LOC_GUARDIAN_NAME { get; set; }
        public string LOC_GUARDIAN_RELATIONSHIP { get; set; }
        public string LOC_GUARDIAN_MOBILE { get; set; }
        public string LOCAL_GURDIAN_NATIONAL_ID { get; set; }
        public string LOCAL_GURDIAN_PASSPORT_NO { get; set; }
        public string STUDENT_PHOTO_PATH { get; set; }
        public string PROXIMITY_NUM { get; set; }
        public string EXIT_REASONS { get; set; }
        public string ATTRIBUTE1 { get; set; }
        public string ATTRIBUTE2 { get; set; }
        public string ATTRIBUTE3 { get; set; }
        public string ATTRIBUTE4 { get; set; }
        public string ATTRIBUTE5 { get; set; }
        public string ATTRIBUTE6 { get; set; }
        public string ATTRIBUTE7 { get; set; }
        public string ATTRIBUTE8 { get; set; }
        public string ATTRIBUTE9 { get; set; }
        public string ATTRIBUTE10 { get; set; }
        public Nullable<long> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public Nullable<long> LAST_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DATE { get; set; }
        public string SYNC_STATUS { get; set; }
        public Nullable<int> READMISSION_SESSION_ID { get; set; }
    }
}
