//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automated_Attendance_System.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BSS_SERVICE_SETTINGS
    {
        public int SERVICE_ID { get; set; }
        public string SERVICE_NAME { get; set; }
        public string SERVICE_SHORT_NAME { get; set; }
        public int EMAIL { get; set; }
        public Nullable<int> ALTERNATIVE_EMAIL { get; set; }
        public bool STATUS { get; set; }
        public string ATTRIBUTE1 { get; set; }
        public string ATTRIBUTE2 { get; set; }
        public string ATTRIBUTE3 { get; set; }
        public string ATTRIBUTE4 { get; set; }
        public string ATTRIBUTE5 { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public Nullable<int> UPDATE_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
    }
}
