//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automated_Attendance_System.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BSS_STUDENT
    {
        public int STUDENT_HEADER_ID { get; set; }
        public string STUDENT_ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string MIDDLE_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string NICK_NAME { get; set; }
        public string PRES_HOLDING_NO { get; set; }
        public string PRES_STREET { get; set; }
        public string PRES_AREA { get; set; }
        public Nullable<int> PRES_THANA_ID { get; set; }
        public string PRES_POST_CODE { get; set; }
        public Nullable<int> PRES_CITY_ID { get; set; }
        public Nullable<int> PRES_DIVISION_ID { get; set; }
        public Nullable<int> PRES_COUNTRY_ID { get; set; }
        public string PERM_HOLDING_NO { get; set; }
        public string PERM_STREET { get; set; }
        public string PERM_AREA { get; set; }
        public string PERM_POST_CODE { get; set; }
        public Nullable<int> PERM_THANA_ID { get; set; }
        public Nullable<int> PERM_CITY_ID { get; set; }
        public Nullable<int> PERM_DIVISION_ID { get; set; }
        public Nullable<int> PERM_COUNTRY_ID { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> BIRTH_CITY { get; set; }
        public Nullable<int> BIRTH_COUNTRY { get; set; }
        public string PLACE_OF_BIRTH { get; set; }
        public Nullable<System.DateTime> ADMISSION_DATE { get; set; }
        public Nullable<int> ADMISSION_SESSION_ID { get; set; }
        public Nullable<int> ADMISSION_CLASS_ID { get; set; }
        public Nullable<int> ADMISSION_SECTION_ID { get; set; }
        public Nullable<int> ADMISSION_SHIFT { get; set; }
        public Nullable<int> SESSION_ID { get; set; }
        public Nullable<int> CLASS_ID { get; set; }
        public Nullable<int> SECTION_ID { get; set; }
        public Nullable<int> SHIFT { get; set; }
        public Nullable<int> CAMPUS_ID { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public string GENDER { get; set; }
        public string RELIGION { get; set; }
        public string RES_PHONE { get; set; }
        public string MOBILE { get; set; }
        public string EMAIL { get; set; }
        public string BLOOD_GROUP { get; set; }
        public string NATIONALITY { get; set; }
        public string BIRTH_CERTIFICATE_NO { get; set; }
        public string PASSPORT_NO { get; set; }
        public string MEDICAL_HISTORY { get; set; }
        public string EMERGENCY_MEDICAL_ACTION { get; set; }
        public string FATHER_FIRST_NAME { get; set; }
        public string FATHER_MIDDLE_NAME { get; set; }
        public string FATHER_LAST_NAME { get; set; }
        public string FATHER_EDUCATION { get; set; }
        public string FATHER_EDUCATION_DETAILS { get; set; }
        public string FATHER_OCCUPATION { get; set; }
        public string FATHER_OCCUPATION_DETAILS { get; set; }
        public string FATHER_OFFICE_ADDRESS { get; set; }
        public string FATHER_OFFICE_PHONE { get; set; }
        public string FATHER_MOBILE { get; set; }
        public string FATHER_NATIONAL_ID { get; set; }
        public string FATHER_PASSPORT_NO { get; set; }
        public string MOTHER_FIRST_NAME { get; set; }
        public string MOTHER_MIDDLE_NAME { get; set; }
        public string MOTHER_LAST_NAME { get; set; }
        public string MOTHER_EDUCATION { get; set; }
        public string MOTHER_EDUCATION_DETAILS { get; set; }
        public string MOTHER_OCCUPATION { get; set; }
        public string MOTHER_OCCUPATION_DETAILS { get; set; }
        public string MOTHER_OFFICE_ADDRESS { get; set; }
        public string MOTHER_OFFICE_PHONE { get; set; }
        public string MOTHER_MOBILE { get; set; }
        public string MOTHER_NATIONAL_ID { get; set; }
        public string MOHER_PASSPORT_NO { get; set; }
        public string LOC_GUARDIAN_FIRST_NAME { get; set; }
        public string LOC_GUARDIAN_MIDDLE_NAME { get; set; }
        public string LOC_GUARDIAN_LAST_NAME { get; set; }
        public string LOC_GUARDIAN_RELATIONSHIP { get; set; }
        public string LOC_GUARDIAN_MOBILE { get; set; }
        public string LOCAL_GURDIAN_NATIONAL_ID { get; set; }
        public string LOCAL_GURDIAN_PASSPORT_NO { get; set; }
        public string STUDENT_PHOTO_PATH { get; set; }
        public string PROXIMITY_NUM { get; set; }
        public string EXIT_REASONS { get; set; }
        public string ATTRIBUTE1 { get; set; }
        public string ATTRIBUTE2 { get; set; }
        public string ATTRIBUTE3 { get; set; }
        public string ATTRIBUTE4 { get; set; }
        public string ATTRIBUTE5 { get; set; }
        public string ATTRIBUTE6 { get; set; }
        public string ATTRIBUTE7 { get; set; }
        public string ATTRIBUTE8 { get; set; }
        public string ATTRIBUTE9 { get; set; }
        public string ATTRIBUTE10 { get; set; }
        public Nullable<long> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public Nullable<long> LAST_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DATE { get; set; }
        public Nullable<System.DateTime> EFFECTIVE_FROM { get; set; }
        public Nullable<System.DateTime> EFFECTIVE_TO { get; set; }
        public Nullable<System.DateTime> READMISSION_DATE { get; set; }
        public Nullable<int> READMISSION_SESSION_ID { get; set; }
        public string SYNC_STATUS { get; set; }
        public string ATTRIBUTE11 { get; set; }
        public string ATTRIBUTE12 { get; set; }
        public string ATTRIBUTE13 { get; set; }
        public string ATTRIBUTE14 { get; set; }
        public string ATTRIBUTE15 { get; set; }
        public string ATTRIBUTE16 { get; set; }
        public string ATTRIBUTE17 { get; set; }
        public string ATTRIBUTE18 { get; set; }
        public string ATTRIBUTE19 { get; set; }
        public string ATTRIBUTE20 { get; set; }
        public string ATTRIBUTE21 { get; set; }
        public string ATTRIBUTE22 { get; set; }
        public string ATTRIBUTE23 { get; set; }
        public string ATTRIBUTE24 { get; set; }
        public string ATTRIBUTE25 { get; set; }
        public string ATTRIBUTE26 { get; set; }
        public string ATTRIBUTE27 { get; set; }
        public string ATTRIBUTE28 { get; set; }
        public string ATTRIBUTE29 { get; set; }
        public string ATTRIBUTE30 { get; set; }
    }
}
