//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automated_Attendance_System.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BSS_ATTENDANCE_DEVICES
    {
        public int DeviceId { get; set; }
        public string DeviceName { get; set; }
        public string DeviceIP { get; set; }
        public string DevicePort { get; set; }
        public Nullable<int> DeviceLocation { get; set; }
        public Nullable<int> DeviceFor { get; set; }
        public string DeviceSerial { get; set; }
        public string DeviceMAC { get; set; }
        public string DeviceFirmwareVersion { get; set; }
        public string DeviceSDKVersion { get; set; }
        public string DeviceProductCode { get; set; }
        public string DeviceMachineNumber { get; set; }
        public Nullable<System.DateTime> DeviceLastSynced { get; set; }
        public Nullable<int> DeviceAdminCount { get; set; }
        public Nullable<int> DeviceUserCount { get; set; }
        public Nullable<int> DeviceTrxCount { get; set; }
        public bool Status { get; set; }
        public string ATTRIBUTE1 { get; set; }
        public string ATTRIBUTE2 { get; set; }
        public string ATTRIBUTE3 { get; set; }
        public string ATTRIBUTE4 { get; set; }
        public string ATTRIBUTE5 { get; set; }
        public System.DateTime DeviceAddedDate { get; set; }
        public Nullable<int> DeviceAddedBy { get; set; }
        public Nullable<System.DateTime> DeviceUpdateDate { get; set; }
        public Nullable<int> DeviceUpdatedBy { get; set; }
    }
}
