//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automated_Attendance_System.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BSS_STUDENT_BILL_VW
    {
        public int BILL_HEADER_ID { get; set; }
        public string BILL_NO { get; set; }
        public Nullable<System.DateTime> BILL_DATE { get; set; }
        public Nullable<int> SESSION_ID { get; set; }
        public Nullable<int> STUDENT_HEADER_ID { get; set; }
        public string STUDENT_ID { get; set; }
        public Nullable<int> CLASS_ID { get; set; }
        public Nullable<int> SECTION_ID { get; set; }
        public Nullable<int> SHIFT { get; set; }
        public Nullable<int> SCHOOL_ID { get; set; }
        public Nullable<int> BRANCH_ID { get; set; }
        public Nullable<decimal> DISCOUNT { get; set; }
        public Nullable<int> PERIOD_ID { get; set; }
        public string STUDENT_NAME { get; set; }
        public string CLASS_NAME { get; set; }
        public string SECTION_NAME { get; set; }
        public Nullable<int> CLASS_DETAILS { get; set; }
        public string CAMPUS_NAME { get; set; }
        public string FLEX_VALUE { get; set; }
        public string SESSION_NAME { get; set; }
        public string USER_NAME { get; set; }
        public string EMP_NAME { get; set; }
        public string PERIOD_NAME { get; set; }
        public string ATTRIBUTE1 { get; set; }
        public string ATTRIBUTE2 { get; set; }
        public string ATTRIBUTE3 { get; set; }
        public string ATTRIBUTE4 { get; set; }
        public string ATTRIBUTE5 { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public Nullable<int> LAST_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DATE { get; set; }
        public int BILL_DTL_ID { get; set; }
        public string RCV_TYPE { get; set; }
        public Nullable<decimal> BILL_AMOUNT { get; set; }
        public Nullable<decimal> ACTUAL_RCV_AMOUNT { get; set; }
        public string VAT_AMT { get; set; }
        public Nullable<decimal> DISC_AMOUNT { get; set; }
        public string SEGMENT1 { get; set; }
        public string SEGMENT2 { get; set; }
        public string SEGMENT3 { get; set; }
        public string SEGMENT4 { get; set; }
        public string SEGMENT5 { get; set; }
        public string SEGMENT6 { get; set; }
        public string SEGMENT7 { get; set; }
        public string DISC_ACC { get; set; }
        public Nullable<int> BSL_PERIOD_ID { get; set; }
        public string REMARKS { get; set; }
        public string LINE_ATTRIBUTE1 { get; set; }
        public string LINE_ATTRIBUTE2 { get; set; }
        public string LINE_ATTRIBUTE3 { get; set; }
        public string LINE_ATTRIBUTE4 { get; set; }
        public string LINE_ATTRIBUTE5 { get; set; }
        public Nullable<long> LINE_CREATED_BY { get; set; }
        public Nullable<System.DateTime> LINE_CREATION_DATE { get; set; }
    }
}
