//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automated_Attendance_System.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BSS_SMS_HISTORY
    {
        public long SMS_ID { get; set; }
        public string SENT_TO { get; set; }
        public string SMS_SUBJECT { get; set; }
        public string SMS_CONTENT { get; set; }
        public Nullable<bool> IS_SEND { get; set; }
        public Nullable<int> STATUS { get; set; }
        public string STATUS_TEXT { get; set; }
        public Nullable<int> ERROR_CODE { get; set; }
        public string ERROR_TEXT { get; set; }
        public string ATTRIBUTE1 { get; set; }
        public string ATTRIBUTE2 { get; set; }
        public string ATTRIBUTE3 { get; set; }
        public string ATTRIBUTE4 { get; set; }
        public string ATTRIBUTE5 { get; set; }
        public Nullable<long> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public Nullable<long> LAST_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DATE { get; set; }
        public Nullable<System.DateTime> EFFECTIVE_FROM { get; set; }
        public Nullable<System.DateTime> EFFECTIVE_TO { get; set; }
    }
}
