//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automated_Attendance_System.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BSS_ATTENDANCE_ZK
    {
        public int AttendaceID { get; set; }
        public int Enrollment_Number { get; set; }
        public int Machine_Number { get; set; }
        public Nullable<int> InOut_Mode { get; set; }
        public int Verify_Method { get; set; }
        public System.DateTime Punch_Date { get; set; }
        public System.TimeSpan Punch_Time { get; set; }
        public Nullable<int> Work_Code { get; set; }
        public Nullable<bool> Sync_Status { get; set; }
    }
}
