//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automated_Attendance_System.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BSS_ATTENDANCE_DEVICES> BSS_ATTENDANCE_DEVICES { get; set; }
        public virtual DbSet<BSS_ATTENDANCE_ZK> BSS_ATTENDANCE_ZK { get; set; }
        public virtual DbSet<BSS_STUDENT> BSS_STUDENT { get; set; }
        public virtual DbSet<HR_EMPLOYEE> HR_EMPLOYEE { get; set; }
        public virtual DbSet<BSS_SMS_HISTORY> BSS_SMS_HISTORY { get; set; }
        public virtual DbSet<BSS_EMAIL_SETTINGS> BSS_EMAIL_SETTINGS { get; set; }
        public virtual DbSet<BSS_SERVICE_SETTINGS> BSS_SERVICE_SETTINGS { get; set; }
        public virtual DbSet<BSS_STUDENT_VW> BSS_STUDENT_VW { get; set; }
        public virtual DbSet<HR_EMPLOYEE_VW> HR_EMPLOYEE_VW { get; set; }
        public virtual DbSet<BSS_STUDENT_BILL_VW> BSS_STUDENT_BILL_VW { get; set; }
        public virtual DbSet<Tution_Fee_Due_VW> Tution_Fee_Due_VW { get; set; }
    }
}
