//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automated_Attendance_System.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_EMPLOYEE
    {
        public int EMP_HEADER_ID { get; set; }
        public string EMP_ID { get; set; }
        public string EMP_FIRST_NAME { get; set; }
        public string EMP_MIDDLE_NAME { get; set; }
        public string EMP_LAST_NAME { get; set; }
        public string EMP_NICK_NAME { get; set; }
        public Nullable<int> BUSINESS_GROUP_ID { get; set; }
        public Nullable<int> APPLICANT_ID { get; set; }
        public Nullable<int> DEPT_ID { get; set; }
        public Nullable<int> DESIG_ID { get; set; }
        public string PUNCH_CARD_ID { get; set; }
        public string START_TIME { get; set; }
        public string END_TIME { get; set; }
        public Nullable<System.DateTime> JOINING_DATE { get; set; }
        public Nullable<System.DateTime> JOB_END_DATE { get; set; }
        public Nullable<bool> IS_PERMENENT { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public Nullable<System.DateTime> BIRTH_DATE { get; set; }
        public Nullable<System.DateTime> DEATH_DATE { get; set; }
        public Nullable<int> JOB_LOCATION_ID { get; set; }
        public Nullable<int> BASE_OFFICE_ID { get; set; }
        public Nullable<int> UNIT_ID { get; set; }
        public Nullable<int> INTERNAL_LOCATION_ID { get; set; }
        public string PRES_HOLDING_NO { get; set; }
        public string PRES_STREET { get; set; }
        public string PRES_AREA { get; set; }
        public Nullable<int> PRES_THANA_ID { get; set; }
        public string PRES_POST_CODE { get; set; }
        public Nullable<int> PRES_CITY_ID { get; set; }
        public Nullable<int> PRES_DIVISION_ID { get; set; }
        public Nullable<int> PRES_COUNTRY_ID { get; set; }
        public string PERM_HOLDING_NO { get; set; }
        public string PERM_STREET { get; set; }
        public string PERM_AREA { get; set; }
        public Nullable<int> PERM_THANA_ID { get; set; }
        public string PERM_POST_CODE { get; set; }
        public Nullable<int> PERM_CITY_ID { get; set; }
        public Nullable<int> PERM_DIVISION_ID { get; set; }
        public Nullable<int> PERM_COUNTRY_ID { get; set; }
        public Nullable<bool> GENDER { get; set; }
        public string RELIGION { get; set; }
        public string PLACE_OF_BIRTH { get; set; }
        public Nullable<int> BIRTH_COUNTRY { get; set; }
        public Nullable<int> BIRTH_CITY { get; set; }
        public string NATIONALITY { get; set; }
        public string PASSPORT_NO { get; set; }
        public string NATIONAL_ID { get; set; }
        public string SOCIAL_SECURITY_ID { get; set; }
        public string DRIVING_LICENSE_NO { get; set; }
        public string BLOOD_GROUP { get; set; }
        public string MARITAL_STATUS { get; set; }
        public string IS_STUDENT { get; set; }
        public string WORK_PHONE { get; set; }
        public string MOBILE { get; set; }
        public string PHONE { get; set; }
        public string EMAIL { get; set; }
        public string EMAIL_2 { get; set; }
        public string FATHER_FIRST_NAME { get; set; }
        public string FATHER_MIDDLE_NAME { get; set; }
        public string FATHER_LAST_NAME { get; set; }
        public string FATHER_CONTACT_NO { get; set; }
        public string FATHER_NATIONAL_ID { get; set; }
        public string MOTHER_FIRST_NAME { get; set; }
        public string MOTHER_MIDDLE_NAME { get; set; }
        public string MOTHER_LAST_NAME { get; set; }
        public string MOTHER_CONTACT_NO { get; set; }
        public string MOTHER_NATIONAL_ID { get; set; }
        public string SPOUSE_FIRST_NAME { get; set; }
        public string SPOUSE_MIDDLE_NAME { get; set; }
        public string SPOUSE_LAST_NAME { get; set; }
        public string SPOUSE_CONTACT_NO { get; set; }
        public string SPOUSE_NATIONAL_ID { get; set; }
        public Nullable<int> NO_OF_DEPENDENT { get; set; }
        public Nullable<System.DateTime> BACKGROUND_CHECK_DATE { get; set; }
        public Nullable<int> BACKGROUND_CHECK_BY { get; set; }
        public Nullable<bool> BACKGROUND_CHECK_STATUS { get; set; }
        public string LAST_MEDICAL_STATUS { get; set; }
        public Nullable<System.DateTime> LAST_MEDICAL_CHECK_DATE { get; set; }
        public string MEDICAL_HISTORY { get; set; }
        public string SIGNATURE { get; set; }
        public string IMG_URL { get; set; }
        public string ATTRIBUTE1 { get; set; }
        public string ATTRIBUTE2 { get; set; }
        public string ATTRIBUTE3 { get; set; }
        public string ATTRIBUTE4 { get; set; }
        public string ATTRIBUTE5 { get; set; }
        public string ATTRIBUTE6 { get; set; }
        public string ATTRIBUTE7 { get; set; }
        public string ATTRIBUTE8 { get; set; }
        public string ATTRIBUTE9 { get; set; }
        public string ATTRIBUTE10 { get; set; }
        public string ATTRIBUTE11 { get; set; }
        public string ATTRIBUTE12 { get; set; }
        public string ATTRIBUTE13 { get; set; }
        public string ATTRIBUTE14 { get; set; }
        public string ATTRIBUTE15 { get; set; }
        public Nullable<long> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public Nullable<long> LAST_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DATE { get; set; }
        public Nullable<System.DateTime> EFFECTIVE_FROM { get; set; }
        public Nullable<System.DateTime> EFFECTIVE_TO { get; set; }
        public string SYNC_STATUS { get; set; }
        public Nullable<System.DateTime> REJOINING_DATE { get; set; }
    }
}
