//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automated_Attendance_System.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_EMPLOYEE_VW
    {
        public int EMP_HEADER_ID { get; set; }
        public string EMP_ID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> DEPT_ID { get; set; }
        public string Department { get; set; }
        public Nullable<int> DESIG_ID { get; set; }
        public string NID { get; set; }
        public string PASSPORT { get; set; }
        public string EMAIL { get; set; }
        public string EMAIL_2 { get; set; }
        public string DESIGNATION { get; set; }
        public string PHONE { get; set; }
        public string MOBILE { get; set; }
        public string START_TIME { get; set; }
        public string END_TIME { get; set; }
        public Nullable<System.DateTime> JOINING_DATE { get; set; }
        public string REJOIN_DATE { get; set; }
        public Nullable<System.DateTime> JOB_END_DATE { get; set; }
        public Nullable<int> Campus { get; set; }
        public string PresentAdderss { get; set; }
        public string PermanentAdderss { get; set; }
        public string FATHER_NAME { get; set; }
        public string FATHER_CONTACT_NO { get; set; }
        public string MOTHER_NAME { get; set; }
        public string MOTHER_CONTACT_NO { get; set; }
        public Nullable<int> JOB_LOCATION_ID { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public string NATIONAL_ID { get; set; }
        public Nullable<bool> GENDER { get; set; }
        public Nullable<System.DateTime> BIRTH_DATE { get; set; }
    }
}
