//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automated_Attendance_System.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tution_Fee_Due_VW
    {
        public string STUDENT_ID { get; set; }
        public string STUDENT_NAME { get; set; }
        public string CLASS_NAME { get; set; }
        public string SECTION_NAME { get; set; }
        public string LAST_PAID_MONTH { get; set; }
        public string MOBILE { get; set; }
        public int PERIOD_ID { get; set; }
    }
}
